# Site settings
name: firewalld
email: twoerner<AT>redhat.com
author: Thomas Woerner
lang: "en"

keywords: firewalld, firewall, linux, security, netfilter, dbus, daemon
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the firewalld project homepage!
  Firewalld provides a dynamically managed firewall with support for network/firewall zones that defines the trust level of network connections or interfaces.

baseurl:
url: firewalld.github.io
production_url: http://firewalld.org

# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized, slim-pickins-jekyll-theme-master]


# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

feed:
  path: atom.xml
  
# Compress our Css
sass:
    style: :compressed

permalink: /:year/:month/:title
paginate: 5
paginate_path: "/blog/page/:num/"

#### SEO Stuff
# Google Analytics
google_universal_analytics: UA-83693467-1
google_universal_analytics_cookiedomain: auto
